version: "2"

services:
  ####################### Backend Definition #######################
  backend:
    container_name: eagle_backend
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - ./api/:/app/api/
    depends_on: 
      - minio
    networks:
      - eagle
      
  ####################### Minio Definition #######################
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "443:9000"
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - minio_data:/data
    networks:
      - eagle

####################### Mongo Definition #######################
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"    
    environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null    
    ports:
        - 27017:27017
    command: mongod --logpath=/dev/null # --quiet
    networks:
      - eagle
      
####################### Networks Definition #######################
networks:
  eagle:
    driver: "bridge"

volumes:
  minio_data: